// WORKING
POST http://localhost:8080/v8/artifacts/events?teamId=asdf&slug=fdsa HTTP/1.1
x-artifact-client-ci: asdf
x-artifact-client-interactive: 0
Content-Type: application/json

[
  {
    "sessionId": "04a314a8-c6c3-4c9d-99d8-4afa723045d8",	
    "source": "LOCAL",
    "hash": "becee9a9-5cd3-473e-8108-9f327a3a337c",
    "event": "MISS"
  },
  {
    "sessionId": "04a314a8-c6c3-4c9d-99d8-4afa723045d8",
    "source": "REMOTE",
    "hash": "becee9a9-5cd3-473e-8108-9f327a3a337c",
    "event": "HIT",
    "duration": 712
  }
]

###

// FAILING
POST http://localhost:8080/v8/artifacts/events?teamId=asdf&slug=fdsa HTTP/1.1
x-artifact-client-ci: asdf
x-artifact-client-interactive: 0
Content-Type: application/json

[
  {
    "sessionId": "c238058e-0eb9-49f0-b486-d78708befc4e",	
    "hash": "becee9a9-5cd3-473e-8108-9f327a3a337c",
    "event": "MISS"
  },
  {
    "sessionId": "c238058e-0eb9-49f0-b486-d78708befc4e",
    "source": "REMOTE",
    "hash": "becee9a9-5cd3-473e-8108-9f327a3a337c",
    "event": "HIT",
    "duration": 712
  }
]